export const configuration = () => ({
  NODE_ENV: process.env.NODE_ENV,
  BASE_DOMAIN: process.env.BASE_DOMAIN,
  PORT: process.env.PORT || 3001,
  DATABASE_URL: process.env.DATABASE_URL,
  CLIENT_URL: process.env.CLIENT_URL,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  COURIER_BRAND_ID: process.env.COURIER_BRAND_ID,
  COURIER_AUTH_TOKEN: process.env.COURIER_AUTH_TOKEN,
  CONFIRM_ACCOUNT_NOTIFICATION_ID: process.env.CONFIRM_ACCOUNT_NOTIFICATION_ID,
  REQUEST_RESET_PASSWORD_NOTIFICATION_ID:
    process.env.REQUEST_RESET_PASSWORD_NOTIFICATION_ID,
});
